### ISSUE TITLE
This webapp can't be translated

### ISSUE THREAD

**Issue by advocatux** [stekalb/outlook-office365.qmlwebcontainer#1]
Please, generate the necessary file (.pot file) so this webapp can be translated to other languages.

Thank you!

**Comment by stekalb** [comment]
Hi advocatux,
I don't see any QML elements which have exposed text at the UI. So I think it's not useful to generate .pot. Otherwise please give me a hint, what should be translatable.

**Comment by advocatux** [comment]
Hi, I see strings to translate in the `action` directory. For example:
```
Action {
    text: i18n.tr("Copy link")
}
```
You can follow the instructions in the `makefile` file, that should work (but change «tagesanzeiger» for the proper name).

Thank you for your work!

**Comment by stekalb** [comment]
Ah, I see :-)
I'll create a new issue: "Remove unused code"
