### ISSUE TITLE
White screen after launching app

### ISSUE THREAD

**Issue by MK1973** [stekalb/outlook-office365.qmlwebcontainer#4]
Expected behavior 

When app launched it should appear list if incoming emails.

Current behavior 

When app opened the list of received emails appeared but immediately switches to blank, white screen. I can only swipe to close the app. 

Cleanning cashe with UT tweak tool did not helped. 

Device: Bq 4.5, N5
Channel: devel
OS: Xenial

**Comment by stekalb** [comment]
That's an issue of the webengine oxide on xenial. So there's nothing I can do currently.

**Comment by MK1973** [comment]
I had the feeling it should be that, there for I was not coming here earlier. Many Thx for confirm.

**Comment by MK1973** [comment]
I had the feeling it should be that, there for I was not coming here earlier. Many Thx to confirm.

**Comment by stekalb** [comment]
fixed
